version: "3"
virtualmachines:
- name: workstation
  image: ubuntu-os-cloud/ubuntu-2204-jammy-v20240607
  machine_type: n1-standard-2
  shell: /bin/bash
  allow_external_ingress:
  - http
  - https
  - high-ports
